[general]
import = ["~/.config/alacritty/themes/catppuccin-latte.toml"]

[terminal.shell]
program = "tmux"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }
size = 10

[window]
dimensions = { columns = 120, lines = 30 }
padding = { x = 8, y = 8 }
opacity = 1.0

[env]
TERM = "alacritty"
