[colors.primary]
background = "#111111"
foreground = "#D5D5D5"
dim_foreground = "#7E7E7E"
bright_foreground = "#D5D5D5"

[colors.cursor]
text = "#111111"
cursor = "#E1E1E1"

[colors.vi_mode_cursor]
text = "#111111"
cursor = "#C5C5C5"

[colors.search.matches]
foreground = "#111111"
background = "#AAAAAA"

[colors.search.focused_match]
foreground = "#111111"
background = "#858585"

[colors.footer_bar]
foreground = "#111111"
background = "#AAAAAA"

[colors.hints.start]
foreground = "#111111"
background = "#8F8F8F"

[colors.hints.end]
foreground = "#111111"
background = "#AAAAAA"

[colors.selection]
text = "#111111"
background = "#E1E1E1"

[colors.normal]
black = "#3C3C3C"
red = "#7C7C7C"
green = "#858585"
yellow = "#8F8F8F"
blue = "#898989"
magenta = "#C3C3C3"
cyan = "#7B7B7B"
white = "#BFBFBF"

[colors.bright]
black = "#525252"
red = "#7C7C7C"
green = "#858585"
yellow = "#8F8F8F"
blue = "#898989"
magenta = "#C3C3C3"
cyan = "#7B7B7B"
white = "#AAAAAA"

[[colors.indexed_colors]]
index = 16
color = "#6D6D6D"

[[colors.indexed_colors]]
index = 17
color = "#E1E1E1"
