# vim:fileencoding=utf-8:foldmethod=marker:filetype=i3config

#: I3 {{{

bindsym $mod+m bar mode toggle

bindsym $mod+Shift+c reload
bindsym $mod+Shift+r restart
bindsym $mod+Shift+e exec "i3-nagbar -f 'pango:JetBrainsMono Nerd Font SemiBold 10' -t warning -m ' Exit request detected' -B 'Yes' 'i3-msg exit'"

#: }}}

#: Volume {{{

set $refresh_i3status killall -SIGUSR1 i3status
bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +10% && $refresh_i3status
bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -10% && $refresh_i3status
bindsym XF86AudioMute exec --no-startup-id pactl set-sink-mute @DEFAULT_SINK@ toggle && $refresh_i3status
bindsym XF86AudioMicMute exec --no-startup-id pactl set-source-mute @DEFAULT_SOURCE@ toggle && $refresh_i3status

#: }}}

#: Terminal {{{

bindsym $mod+Return exec i3-sensible-terminal

#: }}}

#: Window {{{

bindsym $mod+Shift+q kill

#: }}}

#: Window (Launcher) {{{

bindsym $mod+d exec "rofi -modi drun,run -show drun"

#: }}}

#: Window (Focus) {{{

bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right

bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

bindsym $mod+space focus mode_toggle

bindsym $mod+p focus parent
bindsym $mod+n focus child

#: }}}

#: Window (Move) {{{

bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right

bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

#: }}}

#: Window (Split) {{{

bindsym $mod+r split h
bindsym $mod+b split v

#: }}}

#: Window (Layout) {{{

bindsym $mod+f fullscreen toggle

bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

bindsym $mod+Shift+space floating toggle

#: }}}

#: Window (Workspace) {{{

set $ws1  󰼏
set $ws2  󰼐
set $ws3  󰼑
set $ws4  󰼒
set $ws5  󰼓
set $ws6  󰼔
set $ws7  󰼕
set $ws8  󰼖
set $ws9  󰼗
set $ws10 󰿪

bindsym $mod+1 workspace 1:$ws1
bindsym $mod+2 workspace 2:$ws2
bindsym $mod+3 workspace 3:$ws3
bindsym $mod+4 workspace 4:$ws4
bindsym $mod+5 workspace 5:$ws5
bindsym $mod+6 workspace 6:$ws6
bindsym $mod+7 workspace 7:$ws7
bindsym $mod+8 workspace 8:$ws8
bindsym $mod+9 workspace 9:$ws9
bindsym $mod+0 workspace 0:$ws10

bindsym $mod+Shift+1 move container to workspace 1:$ws1
bindsym $mod+Shift+2 move container to workspace 2:$ws2
bindsym $mod+Shift+3 move container to workspace 3:$ws3
bindsym $mod+Shift+4 move container to workspace 4:$ws4
bindsym $mod+Shift+5 move container to workspace 5:$ws5
bindsym $mod+Shift+6 move container to workspace 6:$ws6
bindsym $mod+Shift+7 move container to workspace 7:$ws7
bindsym $mod+Shift+8 move container to workspace 8:$ws8
bindsym $mod+Shift+9 move container to workspace 9:$ws9
bindsym $mod+Shift+0 move container to workspace 0:$ws10

#: }}}
