[global]
frame_color = "#898989"
separator_color= frame
corner_radius=4
origin = bottom-right
offset = 16x16
frame_width=4
separator_height = 4
font = JetBrainsMono Nerd Font 10
width = 512

[urgency_low]
background = "#111111"
foreground = "#D5D5D5"

[urgency_normal]
background = "#111111"
foreground = "#D5D5D5"

[urgency_critical]
background = "#111111"
foreground = "#D5D5D5"
frame_color = "#6D6D6D"
