[global]
frame_color = "#878787"
separator_color= frame
corner_radius=4
origin = bottom-right
offset = 16x16
frame_width=4
separator_height = 4
font = JetBrainsMono Nerd Font 10
width = 512

[urgency_low]
background = "#010101"
foreground = "#DADADA"

[urgency_normal]
background = "#010101"
foreground = "#DADADA"

[urgency_critical]
background = "#010101"
foreground = "#DADADA"
frame_color = "#787878"
