[global]
frame_color = "#858585"
separator_color= frame
corner_radius=4
origin = bottom-right
offset = 16x16
frame_width=4
separator_height = 4
font = JetBrainsMono Nerd Font 10
width = 512

[urgency_low]
background = "#000000"
foreground = "#DEDEDE"

[urgency_normal]
background = "#000000"
foreground = "#DEDEDE"

[urgency_critical]
background = "#000000"
foreground = "#DEDEDE"
frame_color = "#838383"
