return {
  {
    "akinsho/bufferline.nvim",
    dependencies = "nvim-tree/nvim-web-devicons",
    event = "VeryLazy",
    keys = {
      { "<leader>bp", "<Cmd>BufferLineTogglePin<CR>",             desc = "Toggle Pin" },
      { "<leader>bP", "<Cmd>BufferLineGroupClose ungrouped<CR>",  desc = "Delete Non-Pinned Buffers" },
      { "[b",         "<cmd>BufferLineCyclePrev<cr>",             desc = "Prev Buffer" },
      { "]b",         "<cmd>BufferLineCycleNext<cr>",             desc = "Next Buffer" },
      { "[B",         "<cmd>BufferLineMovePrev<cr>",              desc = "Move buffer prev" },
      { "]B",         "<cmd>BufferLineMoveNext<cr>",              desc = "Move buffer next" },
    },
    opts = {
      options = {
        mode = "buffers",
        themable = true,
        numbers = "buffer_id",
        close_command = "bdelete! %d",
        right_mouse_command = "bdelete! %d",
        left_mouse_command = "buffer %d",
        middle_mouse_command = nil,
        indicator = {
          icon = "▎",
          style = "icon",
        },
        buffer_close_icon = "󰅖",
        modified_icon = "● ",
        close_icon = " ",
        left_trunc_marker = " ",
        right_trunc_marker = " ",
        max_name_length = 18,
        max_prefix_length = 15,
        truncate_names = true,
        tab_size = 18,
        diagnostics = true,
        diagnostics_update_in_insert = true,
        diagnostics_update_on_event = true,
        offsets = {
          {
            filetype = "neo-tree",
            text = "EXPLORER",
            text_align = "center",
            separator = true,
          },
        },
        color_icons = true,
        show_buffer_icons = true,
        show_buffer_close_icons = true,
        show_close_icon = true,
        show_tab_indicators = false,
        show_duplicate_prefix = true,
        duplicates_across_groups = true,
        persist_buffer_sort = true,
        move_wraps_at_ends = true,
        -- separator_style = "slant",
        enforce_regular_tabs = true,
        always_show_bufferline = true,
        auto_toggle_bufferline = true,
        hover = {
          enabled = false,
        },
        pick = {
          alphabet = "abcdefghijklmopqrstuvwxyzABCDEFGHIJKLMOPQRSTUVWXYZ1234567890",
        },
      },
    },
  },
}
