#################################
#             Shadows           #
#################################

shadow = false;
shadow-radius = 8;
shadow-opacity = 0.8;
shadow-offset-x = -8;
shadow-offset-y = -8;
shadow-color = "#000000"
crop-shadow-to-monitor = false

#################################
#           Fading              #
#################################

fading = true;
fade-in-step = 0.08;
fade-out-step = 0.08;
fade-delta = 2
no-fading-openclose = false
no-fading-destroyed-argb = false

#################################
#       General Settings        #
#################################

backend = "glx"

vsync = false

detect-rounded-corners = true
detect-client-opacity = true
detect-transient = true
detect-client-leader = false

use-ewmh-active-win = false
use-damage = false

unredir-if-possible = false
unredir-if-possible-delay = 0
